import { useEffect, useMemo, useRef, useState } from 'react'
import { Link, useParams, useSearchParams } from 'react-router-dom'
import { apiFetch, type ApiChapter, type ApiContent, type ApiPosition, type ApiToc } from '../lib/api.ts'
import { ThemeModeSelect, useReaderSettings } from '../lib/settings-context.tsx'

export function ReaderPage() {
  const { bookId = '', chapterId = '' } = useParams()
  const [searchParams] = useSearchParams()
  const editionKey = searchParams.get('editionKey') ?? ''
  const { settings, updateSettings } = useReaderSettings()
  const [content, setContent] = useState<ApiContent | null>(null)
  const [toc, setToc] = useState<ApiToc | null>(null)
  const [position, setPosition] = useState<ApiPosition | null>(null)
  const [positionLoaded, setPositionLoaded] = useState(false)
  const [error, setError] = useState('')
  const articleRef = useRef<HTMLElement>(null)
  const latestPositionRef = useRef<ApiPosition | null>(null)
  useEffect(() => { setContent(null); setToc(null); setPosition(null); setPositionLoaded(false); setError(''); void Promise.all([apiFetch<{ content: { content: ApiContent } }>(`/api/books/${encodeURIComponent(bookId)}/chapters/${encodeURIComponent(chapterId)}?editionKey=${encodeURIComponent(editionKey)}`), apiFetch<{ toc: ApiToc }>(`/api/books/${encodeURIComponent(bookId)}/toc?editionKey=${encodeURIComponent(editionKey)}`), apiFetch<{ position: ApiPosition | null }>(`/api/books/${encodeURIComponent(bookId)}/position?editionKey=${encodeURIComponent(editionKey)}`)]).then(([contentResult, tocResult, positionResult]) => { setContent(contentResult.content.content); setToc(tocResult.toc); setPosition(positionResult.position); setPositionLoaded(true); window.scrollTo({ top: 0, behavior: 'auto' }) }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : '正文加载失败')) }, [bookId, chapterId, editionKey])
  async function persistPosition(input: { paragraphIndex: number; offset: number; version: number }): Promise<void> { if (content === null) return; try { const result = await apiFetch<{ position: ApiPosition }>(`/api/books/${encodeURIComponent(bookId)}/position`, { method: 'POST', body: JSON.stringify({ editionKey, chapterId, chapterUrl: content.chapter.chapterUrl, chapterIndex: content.chapter.index, title: content.chapter.title ?? `第 ${content.chapter.index + 1} 章`, tocRevision: toc?.revision, paragraphIndex: input.paragraphIndex, offset: input.offset, version: input.version }) }); latestPositionRef.current = result.position; setPosition(result.position) } catch { /* 阅读位置保存失败不应阻断阅读 */ } }
  useEffect(() => { latestPositionRef.current = position }, [position])
  useEffect(() => { if (content === null || !positionLoaded) return; const savedPosition = position?.chapterId === chapterId ? position : undefined; if (savedPosition !== undefined) return; const timer = window.setTimeout(() => { void persistPosition({ paragraphIndex: 0, offset: 0, version: (position?.version ?? -1) + 1 }) }, 600); return () => window.clearTimeout(timer) }, [bookId, chapterId, editionKey, content, positionLoaded, position?.version, toc?.revision])
  useEffect(() => { if (content === null || !positionLoaded) return; let timer: number | undefined; const persist = () => { if (articleRef.current === null) return; const paragraphs = [...articleRef.current.querySelectorAll<HTMLElement>('[data-paragraph]')]; const firstVisible = paragraphs.find((paragraph) => paragraph.getBoundingClientRect().bottom > 96); const paragraphIndex = firstVisible === undefined ? 0 : Number(firstVisible.dataset.paragraph ?? 0); const current = latestPositionRef.current; if (current?.chapterId === chapterId && current.paragraphIndex === paragraphIndex) return; const offset = current?.chapterId === chapterId ? current.offset : 0; void persistPosition({ paragraphIndex, offset, version: (current?.version ?? -1) + 1 }) }; const onScroll = () => { if (timer !== undefined) window.clearTimeout(timer); timer = window.setTimeout(() => { timer = undefined; persist() }, 500) }; window.addEventListener('scroll', onScroll, { passive: true }); return () => { window.removeEventListener('scroll', onScroll); if (timer !== undefined) window.clearTimeout(timer) } }, [bookId, chapterId, editionKey, content, positionLoaded, toc?.revision])
  useEffect(() => { if (content === null || position?.chapterId !== chapterId || articleRef.current === null) return; const paragraph = articleRef.current.querySelector<HTMLElement>(`[data-paragraph="${position.paragraphIndex}"]`); paragraph?.scrollIntoView({ block: 'start' }) }, [chapterId, content, position, settings.fontSize, settings.lineHeight])
  const paragraphs = useMemo(() => content?.cleaned.split(/\n+/u).map((text) => text.trim()).filter(Boolean) ?? [], [content])
  const siblings = toc?.chapters.filter((chapter) => chapter.isVolume !== true) ?? []
  const currentIndex = siblings.findIndex((chapter) => chapter.chapterId === chapterId)
  const previous = currentIndex > 0 ? siblings[currentIndex - 1] : undefined
  const next = currentIndex >= 0 ? siblings[currentIndex + 1] : undefined
  if (error.length > 0) return <section className="card"><p className="error">{error}</p><Link className="link" to={`/books/${encodeURIComponent(bookId)}/toc?editionKey=${encodeURIComponent(editionKey)}`}>返回目录</Link></section>
  if (content === null) return <section className="card"><p className="muted">正在读取正文…</p></section>
  return <section className="reader-page"><header className="reader-toolbar"><Link className="button secondary" to={`/books/${encodeURIComponent(bookId)}/toc?editionKey=${encodeURIComponent(editionKey)}`}>目录</Link><div className="reader-title"><span className="muted">{content.chapter.index + 1}</span><strong>{content.chapter.title ?? `第 ${content.chapter.index + 1} 章`}</strong></div><div className="reader-controls"><label>字号 <input type="range" min="15" max="28" value={settings.fontSize} onChange={(event) => void updateSettings({ fontSize: Number(event.target.value) }).catch(() => undefined)} /></label><label>行距 <input type="range" min="1.4" max="2.6" step="0.1" value={settings.lineHeight} onChange={(event) => void updateSettings({ lineHeight: Number(event.target.value) }).catch(() => undefined)} /></label><ThemeModeSelect /></div></header><article className="reader-content" ref={articleRef} style={{ fontSize: `${settings.fontSize}px`, lineHeight: settings.lineHeight }}>{paragraphs.length === 0 ? <p className="muted">本章暂无正文。</p> : paragraphs.map((paragraph, index) => <p data-paragraph={index} key={`${index}:${paragraph.slice(0, 12)}`}>{paragraph}</p>)}</article><nav className="reader-pagination" aria-label="章节导航">{previous === undefined ? <span /> : <Link className="button secondary" to={chapterLink(bookId, previous, editionKey)}>上一章</Link>}<span className="muted">{currentIndex < 0 ? '' : `${currentIndex + 1} / ${siblings.length}`}</span>{next === undefined ? <span /> : <Link className="button" to={chapterLink(bookId, next, editionKey)}>下一章</Link>}</nav></section>
}

function chapterLink(bookId: string, chapter: ApiChapter, editionKey: string): string { return `/books/${encodeURIComponent(bookId)}/read/${encodeURIComponent(chapter.chapterId)}?editionKey=${encodeURIComponent(editionKey)}` }
