shellEmulator: true

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 10080 # 7 days
injectWorkspacePackages: true

packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  '@types/node': 24.0.0
  typescript: 6.0.2
