export { importSources } from './codec/import.ts'
export { createSourceUuid, sameSourceDefinition, sourceDefinitionFingerprint } from './codec/identity.ts'
export { exportSource } from './codec/export.ts'
export { refreshSubscription } from './subscription/refresh.ts'
export { diagnostic, primaryError, safeLocation } from './diagnostics/diagnostics.ts'
export { compileRule, inspectRuleCapabilities } from './rules/compiler.ts'
export { compileSourcePattern } from './rules/pattern-guard.ts'
export type { SourcePatternError, SourcePatternErrorCode, SourcePatternOptions } from './rules/pattern-guard.ts'
export { evaluateRule } from './rules/evaluator.ts'
export { SourceRuleRuntime } from './rules/source-runtime.ts'
export type { SourceRuleBridgeRequest, SourceRuleRuntimeOptions } from './rules/source-runtime.ts'
export { MemoryVariableView, snapshotVariables, variableChanges } from './rules/variables.ts'
export { createRequestPlan } from './runtime/request-plan.ts'
export { resolveSourceRequestReference, resolveSourceRequestUrl, splitSourceRequestUrl } from './runtime/request-url.ts'
export { KeyedConcurrencyHost } from './runtime/concurrency.ts'
export { SourceRateLimiter, systemClockHost, withSourceRateLimit } from './runtime/source-rate-limiter.ts'
export type { SourceRateDiagnostic } from './runtime/source-rate-limiter.ts'
export { replaceFont } from './runtime/font.ts'
export { createSourceSession, MemorySourceScriptCache } from './runtime/source-session.ts'
export type { SourceSession, SourceSessionOptions, SourceSessionOperationContext } from './runtime/source-session.ts'
export type { ParsedSourceRequestUrl } from './runtime/request-url.ts'
export type * from './model/types.ts'
export type * from './rules/types.ts'
export type * from './runtime/contracts.ts'
export type * from './runtime/javascript.ts'
export { discoverBooks, searchBooks, loadBookDetails } from './workflows/discovery.ts'
export { groupSearchCandidates, isAuthorMatch, isBookTitleMatch, normalizeSearchAuthor, normalizeSearchTitle, searchMatchRank } from './workflows/search-aggregation.ts'
export type { SearchAggregationGroup, SearchAggregationItem, SearchMatchRank } from './workflows/search-aggregation.ts'
export { SourceRequestError, SourceRequestRuntime } from './workflows/source-request.ts'
export type { RequestScriptContext, SourceRequestErrorCode, SourceRequestOptions, SourceRequestRuntimeOptions } from './workflows/source-request.ts'
export { loadTableOfContents, loadChapterContent, loadStoredChapterContent, loadChapterContentBatch, decodeImage } from './workflows/reading.ts'
export { reconcileTableOfContents } from './workflows/toc-reconcile.ts'
export type { TocBookPatch, TocCarriedMetadata, TocChange, TocChangeKind, TocReconcileBookState, TocReconcileInput, TocReconcileResult } from './workflows/toc-reconcile.ts'
export type * from './workflows/types.ts'
